# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdf_processor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pdf_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pdf_processor.proto\x12\rpdf_processor\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"0\n\nPdfRequest\x12\x10\n\x08pdf_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\\\n\x11PdfStructResponse\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa8\x01\n\x0cPdfProcessor\x12K\n\nProcessPdf\x12\x19.pdf_processor.PdfRequest\x1a .pdf_processor.PdfStructResponse\"\x00\x12K\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\".pdf_processor.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFREQUEST']._serialized_start=97
  _globals['_PDFREQUEST']._serialized_end=145
  _globals['_PDFSTRUCTRESPONSE']._serialized_start=147
  _globals['_PDFSTRUCTRESPONSE']._serialized_end=239
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=241
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=278
  _globals['_PDFPROCESSOR']._serialized_start=281
  _globals['_PDFPROCESSOR']._serialized_end=449
# @@protoc_insertion_point(module_scope)
